### PR TITLE
Styled privacy consent

### LINKED ISSUE #8: Style privacy consent page
Style this up a bit.

CleanShot 2023-05-04 at 19 12 13@2x

### PR DESCRIPTION
**Pull request by sanitybit**
Resolves #8 if this saves you any time; nothing too fancy (see attached screenshot).

image

### CODE REVIEW

**Comment by jessejanderson** [comment]
Nice - this works for me for now.

I introduced some conflicts for you here though. 🙃

Primarily, the `<ul>` shouldn't be inside of `<p>` so I moved the closing tag here. 
Everything else was just indenting mostly.

CleanShot 2023-05-04 at 20 14 12@2x

**Comment by sanitybit** [comment]
Are you using prettier to do the HTML linting?

**Comment by jessejanderson** [comment]
Yeah, I added prettier and eslint with this PR earlier today: https://github.com/jessejanderson/skylink/pull/7

**Comment by sanitybit** [comment]
Okay, I ran prettier on it too, but it still throws some code issues issue warnings in the PR check? I think it's all functioning (and passes conflicts).

**Comment by jessejanderson** [comment]
Beat you to the punch 😅 (unless there's more you were changing?)

**Comment by sanitybit** [comment]
@jessejanderson Okay, so prettier is opinionated and wants closing slashes on void elements (w3 only warns on this, so not a big deal). But I am still getting errors on prettier:check locally that are a bit confusing...

```
➜ skylink (styled-consent) ✗ npm run prettier:check

> prettier:check
> prettier --check .

Checking formatting...
extension_packages/ff_build/privacy_consent.html[error] extension_packages/ff_build/privacy_consent.html: SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (145:5)
[error]   143 |             <li>Response HTTP encoding, such as application/dns-message or json</li>
[error]   144 |           </ul>
[error] > 145 |     </p>
[error]       |     ^^^^
[error]   146 |     <p>Please read and accept the full <a href="https://developers.google.com/speed/public-dns/privacy" target="_blank">Google DNS privacy policy</a> before using this addon.</p>
[error]   147 |     <button class="button accept" id="accept">Accept (Continue)</button>
[error]   148 |     <button class="button decline" id="decline">Decline (Remove Extension)</button>
All matched files use Prettier code style!
```

**Comment by sanitybit** [comment]
Derp, that was a build artifact -_-;;

**Comment by jessejanderson** [comment]
Ahh - I ran into that too. It's in the build files, so if you haven't run the build again since fixing you'll still have issues.

**Comment by sanitybit** [comment]
LGTM then :)

**Pull request merged**
