### PR TITLE
Security & Privacy Refactoring + Staging Deprecation

### PR DESCRIPTION
**Pull request by sanitybit**
Since the domain and DID are untrusted input that is being processed by the `content.js` script on every visited website, this is a preemptive security enhancement that validates the domain name and DID format for both JSON (tested on `alice.bsky.sh`) and TXT records.

For what it's worth, I don't think there is much we can do to attack the domain name input that is pulled from `window.location.hostname`, but better safe than sorry.

The DID on the other hand should definitely be checked, since it could contain any combination of characters.

### 1. Domain validation
- The script calls the `getDomainName` function to extract the domain from the current hostname.
- The `isValidDomain` function is called with the extracted domain to check its validity.
  - The function checks if the domain length is within the maximum limit (255 characters).
  - The function tries to create a new `URL` instance with the domain. If the constructor doesn't throw an error, the domain is considered valid. 
    - Using the `URL` constructor lets us easily support domains that contain punycode/international/emoji.
  - If the domain is invalid or exceeds the length limit, the `isValidDomain` function returns `false`.

### 2. DID validation
- The `isValidDID` function is called with the extracted DID string from the DNS TXT records (in `checkForDIDDNS`) or from the HTTPS record (in `checkForDIDHTTPS`).
  - The function checks if the DID length is within the maximum limit of a TXT record string.
    - Setting a length check before the regex prevents a local Denial of Service of the regex function if an absurdly large record is presented.
  - The function tests the DID string against the `didRegex` regular expression to validate its format.
    - The regex uses the [DID syntax rules from w3c](https://w3c.github.io/did-core/#did-syntax), and hard codes the `plc` method.
  - If the DID is invalid or exceeds the length limit, the `isValidDID` function returns `false`.

### 3. Processing
- The `performAction` function is called with the user's privacy consent status.
  - If the privacy consent is accepted, the domain is checked for validity.
  - If the domain is valid, the script looks for a DID in the domain's DNS TXT records (`checkForDIDDNS`) and the well-known HTTPS location (`checkForDIDHTTPS`).
    - In the case of the `checkForDIDHTTPS` function, it also checks to make sure the returned content type is `application/json`.
  - If a valid DID is found in either location, a message with the type `DID_FOUND` and the DID is sent to the background script.
  - If no valid DID is found, a message with the type `DID_NOT_FOUND` is sent to the background script.

If the DID doesn't validate correctly, the `isValidDID` function will return `false`, and the respective functions `checkForDIDDNS` and `checkForDIDHTTPS` will return null. In this case, the `performAction` function will send a message with the type `DID_NOT_FOUND` to the background script.

Tested that this functions as expected in Chrome and Firefox.

### CODE REVIEW

**Review by jessejanderson — APPROVED** [review]
Nice work!

Can you update the changelog?

**Comment by sanitybit** [comment]
Change log updated.

**Comment by sanitybit** [comment]
@jessejanderson Since this is a security focused PR, I slipped in one more change:

When I had added the privacy consent workflow required by Mozilla, their suggestion was to uninstall the extension if the user declined a privacy policy for required functionality. This uses the management API so I included the permission.

When I was reading documentation about the management API, it turns out that `uninstallSelf` does not require the permission to function. I've removed the management permission from both manifests, which should get rid of the "Monitor extension usage and manage themes" type permission explanations in store listings.

**Comment by sanitybit** [comment]
I think I may have figured out how to get the extension working without needing "Access your data for all websites" either, which I think would encourage adoption. Testing now.

I'll also update the manifests to target `1.4.0`.

I saw your message about Discord, I'll hop on when I'm done testing. 🤘🏻

**Comment by sanitybit** [comment]
@jessejanderson Despite a valiant effort to migrate everything in `content.js` into `background.js` (and thereby eliminating the need for `<all_urls>`, I was unable to get a functioning extension together. 

I don't have any further changes for this PR.

**Comment by sanitybit** [comment]
As an aside, I thought it was pretty neat that this project is small enough to feed to GPT-4 and have it generate a mermaid diagram, which can be rendered by GitHub. :)

Here is the extension at the time of this PR.

```mermaid
sequenceDiagram
    participant content as content.js
    participant background as background.js
    participant storage as storage
    participant tabs as tabs
    participant action as action
    participant privacy_consent as privacy_consent.js

    background->>+tabs: onInstalled
    background->>storage: Get privacyConsentAccepted
    alt privacyConsentAccepted
        Note over background: Do nothing
    else Consent not accepted
        tabs->>background: tabs.create({ url: "privacy_consent.html" })
    end

    background->>+runtime: onMessage (SHOW_CONSENT)
    tabs->>background: tabs.create({ url: "privacy_consent.html" })

    runtime->>+tabs: onInstalled
    tabs->>background: setIcon(tab.id, "logo48_gray.png")

    background->>runtime: onMessage (DID_FOUND)
    background->>background: setIcon(sender.tab.id, "logo48.png")
    background->>background: tabsWithDID.set(sender.tab.id, message.did)

    background->>runtime: onMessage (DID_NOT_FOUND)
    background->>background: setIcon(sender.tab.id, "logo48_gray.png")
    background->>background: tabsWithDID.delete(sender.tab.id)

    action->>+background: onClicked
    background->>storage: Get privacyConsentAccepted
    alt privacyConsentAccepted
        Note over background: Do nothing
    else Consent not accepted
        tabs->>background: tabs.create({ url: "privacy_consent.html" })
    end

    action->>+background: onClicked (tab with DID)
    background->>background: Get DID from tabsWithDID
    background->>tabs: tabs.create({ url: `${bskyAppUrl}/profile/${did}` })

    privacy_consent->>storage: Set privacyConsentAccepted to true
    privacy_consent->>privacy_consent: window.close()

    privacy_consent->>+management: uninstallSelf

    storage->>content: Get privacyConsentAccepted
    content->>content: performAction(privacyConsentAccepted)
    alt privacyConsentAccepted
        content->>content: getDomainName()
        content->>content: isValidDomain(domain)
        content->>+content: checkForDIDDNS(domain)
        content->>content: fetch TXT records
        content->>-content: Return domainDID or null
        content->>+content: checkForDIDHTTPS(domain)
        content->>content: fetch well-known location
        content->>-content: Return httpsDID or null

        alt domainDID found
            content->>background: SendMessage { type: "DID_FOUND", did: domainDID }
        else httpsDID found
            content->>background: SendMessage { type: "DID_FOUND", did: httpsDID }
        else DID not found
            content->>background: SendMessage { type: "DID_NOT_FOUND" }
        end

        background->>content: AddListener { type: "GET_DID" }
        content->>content: getDomainName()
        content->>content: isValidDomain(domain)
        content->>+content: checkForDIDDNS(domain)
        content->>content: fetch TXT records
        content->>-content: Return did or null
        content->>background: sendResponse({ did })
    else Consent not accepted
        Note over content: Do nothing
    end

```

**Comment by sanitybit** [comment]
@jessejanderson I finally managed to get the whole thing working in a single `background.js` script, which removes the need for the `<all_urls>` permission and the "this extension can access your data on all sites" extension warnings. 

This should hopefully fix issue #26 that reported the breaking logins on some sites, since it no longer attempts to read or inject anything on the dom (`content.js`). The downside is that this only works with the `tabs` permission and not `activeTab`.

I know you had a past rejection from the Chrome store because in the prior version, `activeTab` would suffice in place of `tabs`, however this `tabs` method is a net improvement in privacy, as before we could access (and interfere with) all *data* in all tabs. In this improved model, we can only access the *tab object metadata* for all tabs (and no tab content); and if the code is reviewed, folks should be able to easily confirm that we only do this for the active tab.

I did try to use `activeTab`, however the `tab` object in this case does not return a `url` property unless the extension is manually clicked on each page that is loaded, which is undesirable for obvious reasons.

This also removes the `management` permission as mentioned up-thread.

These changes allowed for me to get a working Firefox Manifest v3. 🤘🏻

Additionally since it is now supported server side, I merged in the changes related to deprecating staging to avoid any merge conflicts with PR #15.

If you agree with these changes, I think this is ready for a `1.4.0` release.

Here is an updated mermaid.js diagram that you can contrast with the earlier one to understand the changes:

```mermaid
sequenceDiagram
    participant B as background.js
    participant S as Browser Storage
    participant T as Tabs
    participant A as Action
    participant P as privacy_consent.js

    B->>S: get "privacyConsentAccepted"
    S-->>B: return privacyConsentAccepted status
    alt privacyConsentAccepted is true
        B->>T: onUpdated, performAction
        T-->>B: tabId, changeInfo, tab
        B->>S: get "privacyConsentAccepted"
        S-->>B: return privacyConsentAccepted status
        B->>T: checkForDIDDNS or checkForDIDHTTPS
        B->>A: setIcon according to the validation result
        A-->>B: set icon
    else privacyConsentAccepted is false or undefined
        B->>T: create "privacy_consent.html" tab
        T-->>B: tab created
    end
    A->>B: onClicked listener
    B->>S: get "privacyConsentAccepted"
    S-->>B: return privacyConsentAccepted status
    alt privacyConsentAccepted is true
        B->>T: get DID from tabsWithDID
        T-->>B: return DID
        B->>T: create new tab with bskyAppUrl + DID
        T-->>B: new tab created
    else privacyConsentAccepted is false or undefined
        B->>T: create "privacy_consent.html" tab
        T-->>B: tab created
    end
    P->>S: set "privacyConsentAccepted" to true (on "accept" click)
    S-->>P: privacyConsentAccepted set
    P->>P: close window
    P->>P: uninstallSelf (on "decline" click)
```

**Comment by jessejanderson** [comment]
@sanitybit incredible work here, nice!

Gonna prep for submitting to browsers and hope I don't get any grief from Chrome again.

**Review by jessejanderson — APPROVED** [review]

**Pull request merged**
